@startuml
'https://plantuml.com/sequence-diagram

skin rose

header P2P Connection - perspective resolving

actor "Peer (client)" as Peer
boundary "Connection Pool" as pool
control Connection as conn
entity "Perspective resolver" as resolver

autonumber

Peer -> pool ++ : Dial
activate Peer
pool -> conn ++ : Add connection
conn -> resolver ++ : Resolve perspective
resolver --> Peer: Send perspective resolvent
Peer --> resolver : Send perspective resolvent

alt Counters are equal and fallback did not apply
    resolver -> conn : Return //connErrNotResolved//
else Counters are different or fallback applied
    resolver -> conn -- : Return no error\nperspective was resolved
end

alt Perspective was resolved
    conn -> conn : Assign QUIC connection to the\n//Connection// associated with the Peer
else Perspective was not resolved
    conn -> pool : Return //connErrNotResolved//
else the connection was already established
    conn -> pool -- : Return //connErrAlreadyEstablished//
end

alt Error returned from Connection
    pool -> Peer -- : Close QUIC connection with the returned error
    deactivate Peer
end

@enduml